repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.16.1
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
        files: ^api/
      - id: ruff-format
        args: [--check]
        files: ^api/

  - repo: local
    hooks:
      - id: mypy
        name: mypy (api)
        entry: mypy app
        language: system
        pass_filenames: false
        files: ^api/app/
        require_serial: true

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
        args: [--maxkb=500]
      - id: check-merge-conflict
      - id: detect-private-key
