/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Portcullis
 * OpenAPI spec version: 0.2.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import { axiosInstance } from '../lib/axios-instance';
/**
 * Schema for creating a new API key.
 */
export interface ApiKeyCreate {
  name: string;
  scopes?: string[];
}

/**
 * Safe response schema for API key data — no hash, no plaintext.
 */
export interface ApiKeyView {
  id: string;
  name: string;
  key_prefix: string;
  scopes: string[];
  created_at: string;
  last_used_at: string | null;
}

/**
 * Response returned only at creation — includes one-time plaintext.
 */
export interface ApiKeyCreateResponse {
  key: ApiKeyView;
  plaintext: string;
}

export type AuditEventType = typeof AuditEventType[keyof typeof AuditEventType];


export const AuditEventType = {
  auth_failure: 'auth_failure',
  rbac_deny: 'rbac_deny',
  tool_call: 'tool_call',
} as const;

export type AuditLogViewDetail = { [key: string]: unknown };

export type SubjectType = typeof SubjectType[keyof typeof SubjectType];


export const SubjectType = {
  api_key: 'api_key',
  oauth_subject: 'oauth_subject',
} as const;

/**
 * Response schema for a single audit log entry.
 */
export interface AuditLogView {
  id: string;
  tenant_id: string | null;
  subject_id: string | null;
  subject_type: SubjectType | null;
  event_type: AuditEventType;
  server_slug: string | null;
  tool_name: string | null;
  rpc_method: string | null;
  outcome: string;
  client_ip: string | null;
  request_id: string | null;
  detail: AuditLogViewDetail;
  created_at: string;
}

export type ValidationErrorCtx = { [key: string]: unknown };

export interface ValidationError {
  loc: (string | number)[];
  msg: string;
  type: string;
  input?: unknown;
  ctx?: ValidationErrorCtx;
}

export interface HTTPValidationError {
  detail?: ValidationError[];
}

export type PermissionEffect = typeof PermissionEffect[keyof typeof PermissionEffect];


export const PermissionEffect = {
  allow: 'allow',
  deny: 'deny',
} as const;

export type RateLimitAlgorithm = typeof RateLimitAlgorithm[keyof typeof RateLimitAlgorithm];


export const RateLimitAlgorithm = {
  token_bucket: 'token_bucket',
  sliding_window: 'sliding_window',
} as const;

/**
 * Schema for creating a new rate-limit policy.
 */
export interface RateLimitPolicyCreate {
  subject_id?: string | null;
  server_pattern?: string | null;
  tool_pattern?: string | null;
  algorithm: RateLimitAlgorithm;
  /** @exclusiveMinimum 0 */
  request_limit: number;
  /** @exclusiveMinimum 0 */
  window_seconds: number;
  burst_capacity?: number | null;
  priority?: number;
}

/**
 * Schema for updating an existing rate-limit policy (all fields optional).
 */
export interface RateLimitPolicyUpdate {
  request_limit?: number | null;
  window_seconds?: number | null;
  burst_capacity?: number | null;
  priority?: number | null;
}

/**
 * Safe response schema for a rate-limit policy.
 */
export interface RateLimitPolicyView {
  id: string;
  subject_id: string | null;
  server_pattern: string | null;
  tool_pattern: string | null;
  algorithm: RateLimitAlgorithm;
  request_limit: number;
  window_seconds: number;
  burst_capacity: number | null;
  priority: number;
  created_at: string;
  updated_at: string;
}

/**
 * Schema for binding a subject to a role.
 *
 * Use ``subject_type=api_key`` (default) with a UUID string for API keys,
 * or ``subject_type=oauth_subject`` with a JWT ``sub`` claim string.
 */
export interface RoleBindingCreate {
  subject_id: string;
  subject_type?: SubjectType;
}

/**
 * Safe response schema for a role binding.
 */
export interface RoleBindingView {
  id: string;
  role_id: string;
  subject_type: SubjectType;
  subject_id: string;
  created_at: string;
}

/**
 * Schema for creating a new role.
 */
export interface RoleCreate {
  name: string;
}

/**
 * Safe response schema for a role.
 */
export interface RoleView {
  id: string;
  name: string;
  created_at: string;
}

export type ServerAuthMode = typeof ServerAuthMode[keyof typeof ServerAuthMode];


export const ServerAuthMode = {
  none: 'none',
  service_token: 'service_token',
} as const;

export type ServerTransport = typeof ServerTransport[keyof typeof ServerTransport];


export const ServerTransport = {
  streamable_http: 'streamable_http',
} as const;

/**
 * Schema for creating a new MCP server registration.
 */
export interface ServerCreate {
  name: string;
  slug: string;
  upstream_url: string;
  transport?: ServerTransport;
  auth_mode?: ServerAuthMode;
  service_token_env_var?: string | null;
  health_check_path?: string;
}

export type ServerStatus = typeof ServerStatus[keyof typeof ServerStatus];


export const ServerStatus = {
  active: 'active',
  disabled: 'disabled',
  unhealthy: 'unhealthy',
} as const;

/**
 * Schema for updating an existing MCP server registration (all fields optional).
 */
export interface ServerUpdate {
  name?: string | null;
  slug?: string | null;
  upstream_url?: string | null;
  transport?: ServerTransport | null;
  auth_mode?: ServerAuthMode | null;
  service_token_env_var?: string | null;
  health_check_path?: string | null;
  status?: ServerStatus | null;
}

/**
 * Safe response schema for MCP server data (never exposes service_token_env_var).
 */
export interface ServerView {
  id: string;
  tenant_id: string;
  name: string;
  slug: string;
  upstream_url: string;
  transport: ServerTransport;
  auth_mode: ServerAuthMode;
  status: ServerStatus;
  health_check_path: string;
  consecutive_health_failures: number;
  last_health_check_at: string | null;
  created_at: string;
  updated_at: string;
}

/**
 * Schema for creating a tool permission rule on a role.
 */
export interface ToolPermissionCreate {
  server_pattern: string;
  tool_pattern: string;
  effect: PermissionEffect;
  priority?: number;
}

/**
 * Safe response schema for a tool permission rule.
 */
export interface ToolPermissionView {
  id: string;
  role_id: string;
  server_pattern: string;
  tool_pattern: string;
  effect: PermissionEffect;
  priority: number;
  created_at: string;
}

export type ListAuditLogsV1AuditGetParams = {
/**
 * @minimum 1
 * @maximum 200
 */
limit?: number;
/**
 * @minimum 0
 */
offset?: number;
event_type?: AuditEventType | null;
server_slug?: string | null;
};

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export type healthzHealthzGetResponse200 = {
  data: unknown
  status: 200
}

export type healthzHealthzGetResponseSuccess = (healthzHealthzGetResponse200) & {
  headers: Headers;
};
;

export type healthzHealthzGetResponse = (healthzHealthzGetResponseSuccess)

export const getHealthzHealthzGetUrl = () => {




  return `/healthz`
}

/**
 * Return readiness status for the database and Redis connections.
 * @summary Healthz
 */
export const healthzHealthzGet = async ( options?: Parameters<typeof axiosInstance>[1]): Promise<healthzHealthzGetResponse> => {

  return axiosInstance<healthzHealthzGetResponse>(getHealthzHealthzGetUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getHealthzHealthzGetQueryKey = () => {
    return [
    `/healthz`
    ] as const;
    }


export const getHealthzHealthzGetQueryOptions = <TData = Awaited<ReturnType<typeof healthzHealthzGet>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof healthzHealthzGet>>, TError, TData>>, request?: SecondParameter<typeof axiosInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getHealthzHealthzGetQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof healthzHealthzGet>>> = ({ signal }) => healthzHealthzGet({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof healthzHealthzGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type HealthzHealthzGetQueryResult = NonNullable<Awaited<ReturnType<typeof healthzHealthzGet>>>
export type HealthzHealthzGetQueryError = unknown


export function useHealthzHealthzGet<TData = Awaited<ReturnType<typeof healthzHealthzGet>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof healthzHealthzGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof healthzHealthzGet>>,
          TError,
          Awaited<ReturnType<typeof healthzHealthzGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axiosInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useHealthzHealthzGet<TData = Awaited<ReturnType<typeof healthzHealthzGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof healthzHealthzGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof healthzHealthzGet>>,
          TError,
          Awaited<ReturnType<typeof healthzHealthzGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axiosInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useHealthzHealthzGet<TData = Awaited<ReturnType<typeof healthzHealthzGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof healthzHealthzGet>>, TError, TData>>, request?: SecondParameter<typeof axiosInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Healthz
 */

export function useHealthzHealthzGet<TData = Awaited<ReturnType<typeof healthzHealthzGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof healthzHealthzGet>>, TError, TData>>, request?: SecondParameter<typeof axiosInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getHealthzHealthzGetQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}







export type createServerV1ServersPostResponse201 = {
  data: ServerView
  status: 201
}

export type createServerV1ServersPostResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type createServerV1ServersPostResponseSuccess = (createServerV1ServersPostResponse201) & {
  headers: Headers;
};
export type createServerV1ServersPostResponseError = (createServerV1ServersPostResponse422) & {
  headers: Headers;
};

export type createServerV1ServersPostResponse = (createServerV1ServersPostResponseSuccess | createServerV1ServersPostResponseError)

export const getCreateServerV1ServersPostUrl = () => {




  return `/v1/servers`
}

/**
 * Register a new upstream MCP server. Requires admin scope.
 * @summary Create Server
 */
export const createServerV1ServersPost = async (serverCreate: ServerCreate, options?: Parameters<typeof axiosInstance>[1]): Promise<createServerV1ServersPostResponse> => {

  return axiosInstance<createServerV1ServersPostResponse>(getCreateServerV1ServersPostUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(serverCreate)
  }
);}





export const getCreateServerV1ServersPostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createServerV1ServersPost>>, TError,{data: ServerCreate}, TContext>, request?: SecondParameter<typeof axiosInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof createServerV1ServersPost>>, TError,{data: ServerCreate}, TContext> => {

const mutationKey = ['createServerV1ServersPost'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createServerV1ServersPost>>, {data: ServerCreate}> = (props) => {
          const {data} = props ?? {};

          return  createServerV1ServersPost(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CreateServerV1ServersPostMutationResult = NonNullable<Awaited<ReturnType<typeof createServerV1ServersPost>>>
    export type CreateServerV1ServersPostMutationBody = ServerCreate
    export type CreateServerV1ServersPostMutationError = HTTPValidationError

    /**
 * @summary Create Server
 */
export const useCreateServerV1ServersPost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createServerV1ServersPost>>, TError,{data: ServerCreate}, TContext>, request?: SecondParameter<typeof axiosInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createServerV1ServersPost>>,
        TError,
        {data: ServerCreate},
        TContext
      > => {
      return useMutation(getCreateServerV1ServersPostMutationOptions(options), queryClient);
    }

export type listServersV1ServersGetResponse200 = {
  data: ServerView[]
  status: 200
}

export type listServersV1ServersGetResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type listServersV1ServersGetResponseSuccess = (listServersV1ServersGetResponse200) & {
  headers: Headers;
};
export type listServersV1ServersGetResponseError = (listServersV1ServersGetResponse422) & {
  headers: Headers;
};

export type listServersV1ServersGetResponse = (listServersV1ServersGetResponseSuccess | listServersV1ServersGetResponseError)

export const getListServersV1ServersGetUrl = () => {




  return `/v1/servers`
}

/**
 * Return all registered MCP servers.
 * @summary List Servers
 */
export const listServersV1ServersGet = async ( options?: Parameters<typeof axiosInstance>[1]): Promise<listServersV1ServersGetResponse> => {

  return axiosInstance<listServersV1ServersGetResponse>(getListServersV1ServersGetUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getListServersV1ServersGetQueryKey = () => {
    return [
    `/v1/servers`
    ] as const;
    }


export const getListServersV1ServersGetQueryOptions = <TData = Awaited<ReturnType<typeof listServersV1ServersGet>>, TError = HTTPValidationError>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listServersV1ServersGet>>, TError, TData>>, request?: SecondParameter<typeof axiosInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListServersV1ServersGetQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listServersV1ServersGet>>> = ({ signal }) => listServersV1ServersGet({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listServersV1ServersGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListServersV1ServersGetQueryResult = NonNullable<Awaited<ReturnType<typeof listServersV1ServersGet>>>
export type ListServersV1ServersGetQueryError = HTTPValidationError


export function useListServersV1ServersGet<TData = Awaited<ReturnType<typeof listServersV1ServersGet>>, TError = HTTPValidationError>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listServersV1ServersGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listServersV1ServersGet>>,
          TError,
          Awaited<ReturnType<typeof listServersV1ServersGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axiosInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListServersV1ServersGet<TData = Awaited<ReturnType<typeof listServersV1ServersGet>>, TError = HTTPValidationError>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listServersV1ServersGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listServersV1ServersGet>>,
          TError,
          Awaited<ReturnType<typeof listServersV1ServersGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axiosInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListServersV1ServersGet<TData = Awaited<ReturnType<typeof listServersV1ServersGet>>, TError = HTTPValidationError>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listServersV1ServersGet>>, TError, TData>>, request?: SecondParameter<typeof axiosInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List Servers
 */

export function useListServersV1ServersGet<TData = Awaited<ReturnType<typeof listServersV1ServersGet>>, TError = HTTPValidationError>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listServersV1ServersGet>>, TError, TData>>, request?: SecondParameter<typeof axiosInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListServersV1ServersGetQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}







export type getServerV1ServersSlugGetResponse200 = {
  data: ServerView
  status: 200
}

export type getServerV1ServersSlugGetResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type getServerV1ServersSlugGetResponseSuccess = (getServerV1ServersSlugGetResponse200) & {
  headers: Headers;
};
export type getServerV1ServersSlugGetResponseError = (getServerV1ServersSlugGetResponse422) & {
  headers: Headers;
};

export type getServerV1ServersSlugGetResponse = (getServerV1ServersSlugGetResponseSuccess | getServerV1ServersSlugGetResponseError)

export const getGetServerV1ServersSlugGetUrl = (slug: string,) => {




  return `/v1/servers/${slug}`
}

/**
 * Return a single MCP server by slug.
 * @summary Get Server
 */
export const getServerV1ServersSlugGet = async (slug: string, options?: Parameters<typeof axiosInstance>[1]): Promise<getServerV1ServersSlugGetResponse> => {

  return axiosInstance<getServerV1ServersSlugGetResponse>(getGetServerV1ServersSlugGetUrl(slug),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetServerV1ServersSlugGetQueryKey = (slug: string,) => {
    return [
    `/v1/servers/${slug}`
    ] as const;
    }


export const getGetServerV1ServersSlugGetQueryOptions = <TData = Awaited<ReturnType<typeof getServerV1ServersSlugGet>>, TError = HTTPValidationError>(slug: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getServerV1ServersSlugGet>>, TError, TData>>, request?: SecondParameter<typeof axiosInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetServerV1ServersSlugGetQueryKey(slug);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getServerV1ServersSlugGet>>> = ({ signal }) => getServerV1ServersSlugGet(slug, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: slug !== null && slug !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getServerV1ServersSlugGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetServerV1ServersSlugGetQueryResult = NonNullable<Awaited<ReturnType<typeof getServerV1ServersSlugGet>>>
export type GetServerV1ServersSlugGetQueryError = HTTPValidationError


export function useGetServerV1ServersSlugGet<TData = Awaited<ReturnType<typeof getServerV1ServersSlugGet>>, TError = HTTPValidationError>(
 slug: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getServerV1ServersSlugGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getServerV1ServersSlugGet>>,
          TError,
          Awaited<ReturnType<typeof getServerV1ServersSlugGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axiosInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetServerV1ServersSlugGet<TData = Awaited<ReturnType<typeof getServerV1ServersSlugGet>>, TError = HTTPValidationError>(
 slug: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getServerV1ServersSlugGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getServerV1ServersSlugGet>>,
          TError,
          Awaited<ReturnType<typeof getServerV1ServersSlugGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axiosInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetServerV1ServersSlugGet<TData = Awaited<ReturnType<typeof getServerV1ServersSlugGet>>, TError = HTTPValidationError>(
 slug: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getServerV1ServersSlugGet>>, TError, TData>>, request?: SecondParameter<typeof axiosInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Server
 */

export function useGetServerV1ServersSlugGet<TData = Awaited<ReturnType<typeof getServerV1ServersSlugGet>>, TError = HTTPValidationError>(
 slug: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getServerV1ServersSlugGet>>, TError, TData>>, request?: SecondParameter<typeof axiosInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetServerV1ServersSlugGetQueryOptions(slug,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}







export type updateServerV1ServersSlugPatchResponse200 = {
  data: ServerView
  status: 200
}

export type updateServerV1ServersSlugPatchResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type updateServerV1ServersSlugPatchResponseSuccess = (updateServerV1ServersSlugPatchResponse200) & {
  headers: Headers;
};
export type updateServerV1ServersSlugPatchResponseError = (updateServerV1ServersSlugPatchResponse422) & {
  headers: Headers;
};

export type updateServerV1ServersSlugPatchResponse = (updateServerV1ServersSlugPatchResponseSuccess | updateServerV1ServersSlugPatchResponseError)

export const getUpdateServerV1ServersSlugPatchUrl = (slug: string,) => {




  return `/v1/servers/${slug}`
}

/**
 * Update an existing MCP server registration. Requires admin scope.
 * @summary Update Server
 */
export const updateServerV1ServersSlugPatch = async (slug: string,
    serverUpdate: ServerUpdate, options?: Parameters<typeof axiosInstance>[1]): Promise<updateServerV1ServersSlugPatchResponse> => {

  return axiosInstance<updateServerV1ServersSlugPatchResponse>(getUpdateServerV1ServersSlugPatchUrl(slug),
  {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(serverUpdate)
  }
);}





export const getUpdateServerV1ServersSlugPatchMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateServerV1ServersSlugPatch>>, TError,{slug: string;data: ServerUpdate}, TContext>, request?: SecondParameter<typeof axiosInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof updateServerV1ServersSlugPatch>>, TError,{slug: string;data: ServerUpdate}, TContext> => {

const mutationKey = ['updateServerV1ServersSlugPatch'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateServerV1ServersSlugPatch>>, {slug: string;data: ServerUpdate}> = (props) => {
          const {slug,data} = props ?? {};

          return  updateServerV1ServersSlugPatch(slug,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UpdateServerV1ServersSlugPatchMutationResult = NonNullable<Awaited<ReturnType<typeof updateServerV1ServersSlugPatch>>>
    export type UpdateServerV1ServersSlugPatchMutationBody = ServerUpdate
    export type UpdateServerV1ServersSlugPatchMutationError = HTTPValidationError

    /**
 * @summary Update Server
 */
export const useUpdateServerV1ServersSlugPatch = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateServerV1ServersSlugPatch>>, TError,{slug: string;data: ServerUpdate}, TContext>, request?: SecondParameter<typeof axiosInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateServerV1ServersSlugPatch>>,
        TError,
        {slug: string;data: ServerUpdate},
        TContext
      > => {
      return useMutation(getUpdateServerV1ServersSlugPatchMutationOptions(options), queryClient);
    }

export type deleteServerV1ServersSlugDeleteResponse204 = {
  data: void
  status: 204
}

export type deleteServerV1ServersSlugDeleteResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type deleteServerV1ServersSlugDeleteResponseSuccess = (deleteServerV1ServersSlugDeleteResponse204) & {
  headers: Headers;
};
export type deleteServerV1ServersSlugDeleteResponseError = (deleteServerV1ServersSlugDeleteResponse422) & {
  headers: Headers;
};

export type deleteServerV1ServersSlugDeleteResponse = (deleteServerV1ServersSlugDeleteResponseSuccess | deleteServerV1ServersSlugDeleteResponseError)

export const getDeleteServerV1ServersSlugDeleteUrl = (slug: string,) => {




  return `/v1/servers/${slug}`
}

/**
 * Delete an MCP server registration. Requires admin scope.
 * @summary Delete Server
 */
export const deleteServerV1ServersSlugDelete = async (slug: string, options?: Parameters<typeof axiosInstance>[1]): Promise<deleteServerV1ServersSlugDeleteResponse> => {

  return axiosInstance<deleteServerV1ServersSlugDeleteResponse>(getDeleteServerV1ServersSlugDeleteUrl(slug),
  {
    ...options,
    method: 'DELETE'


  }
);}





export const getDeleteServerV1ServersSlugDeleteMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteServerV1ServersSlugDelete>>, TError,{slug: string}, TContext>, request?: SecondParameter<typeof axiosInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteServerV1ServersSlugDelete>>, TError,{slug: string}, TContext> => {

const mutationKey = ['deleteServerV1ServersSlugDelete'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteServerV1ServersSlugDelete>>, {slug: string}> = (props) => {
          const {slug} = props ?? {};

          return  deleteServerV1ServersSlugDelete(slug,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteServerV1ServersSlugDeleteMutationResult = NonNullable<Awaited<ReturnType<typeof deleteServerV1ServersSlugDelete>>>

    export type DeleteServerV1ServersSlugDeleteMutationError = HTTPValidationError

    /**
 * @summary Delete Server
 */
export const useDeleteServerV1ServersSlugDelete = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteServerV1ServersSlugDelete>>, TError,{slug: string}, TContext>, request?: SecondParameter<typeof axiosInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteServerV1ServersSlugDelete>>,
        TError,
        {slug: string},
        TContext
      > => {
      return useMutation(getDeleteServerV1ServersSlugDeleteMutationOptions(options), queryClient);
    }

export type triggerHealthProbeV1ServersSlugHealthPostResponse200 = {
  data: unknown
  status: 200
}

export type triggerHealthProbeV1ServersSlugHealthPostResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type triggerHealthProbeV1ServersSlugHealthPostResponseSuccess = (triggerHealthProbeV1ServersSlugHealthPostResponse200) & {
  headers: Headers;
};
export type triggerHealthProbeV1ServersSlugHealthPostResponseError = (triggerHealthProbeV1ServersSlugHealthPostResponse422) & {
  headers: Headers;
};

export type triggerHealthProbeV1ServersSlugHealthPostResponse = (triggerHealthProbeV1ServersSlugHealthPostResponseSuccess | triggerHealthProbeV1ServersSlugHealthPostResponseError)

export const getTriggerHealthProbeV1ServersSlugHealthPostUrl = (slug: string,) => {




  return `/v1/servers/${slug}/health`
}

/**
 * Trigger an immediate health probe for the specified server.
 * @summary Trigger Health Probe
 */
export const triggerHealthProbeV1ServersSlugHealthPost = async (slug: string, options?: Parameters<typeof axiosInstance>[1]): Promise<triggerHealthProbeV1ServersSlugHealthPostResponse> => {

  return axiosInstance<triggerHealthProbeV1ServersSlugHealthPostResponse>(getTriggerHealthProbeV1ServersSlugHealthPostUrl(slug),
  {
    ...options,
    method: 'POST'


  }
);}





export const getTriggerHealthProbeV1ServersSlugHealthPostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof triggerHealthProbeV1ServersSlugHealthPost>>, TError,{slug: string}, TContext>, request?: SecondParameter<typeof axiosInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof triggerHealthProbeV1ServersSlugHealthPost>>, TError,{slug: string}, TContext> => {

const mutationKey = ['triggerHealthProbeV1ServersSlugHealthPost'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof triggerHealthProbeV1ServersSlugHealthPost>>, {slug: string}> = (props) => {
          const {slug} = props ?? {};

          return  triggerHealthProbeV1ServersSlugHealthPost(slug,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type TriggerHealthProbeV1ServersSlugHealthPostMutationResult = NonNullable<Awaited<ReturnType<typeof triggerHealthProbeV1ServersSlugHealthPost>>>

    export type TriggerHealthProbeV1ServersSlugHealthPostMutationError = HTTPValidationError

    /**
 * @summary Trigger Health Probe
 */
export const useTriggerHealthProbeV1ServersSlugHealthPost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof triggerHealthProbeV1ServersSlugHealthPost>>, TError,{slug: string}, TContext>, request?: SecondParameter<typeof axiosInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof triggerHealthProbeV1ServersSlugHealthPost>>,
        TError,
        {slug: string},
        TContext
      > => {
      return useMutation(getTriggerHealthProbeV1ServersSlugHealthPostMutationOptions(options), queryClient);
    }

export type createApiKeyV1ApiKeysPostResponse201 = {
  data: ApiKeyCreateResponse
  status: 201
}

export type createApiKeyV1ApiKeysPostResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type createApiKeyV1ApiKeysPostResponseSuccess = (createApiKeyV1ApiKeysPostResponse201) & {
  headers: Headers;
};
export type createApiKeyV1ApiKeysPostResponseError = (createApiKeyV1ApiKeysPostResponse422) & {
  headers: Headers;
};

export type createApiKeyV1ApiKeysPostResponse = (createApiKeyV1ApiKeysPostResponseSuccess | createApiKeyV1ApiKeysPostResponseError)

export const getCreateApiKeyV1ApiKeysPostUrl = () => {




  return `/v1/api-keys`
}

/**
 * Issue a new API key. Requires admin scope.
 *
 * The plaintext key is returned once and never stored.
 * @summary Create Api Key
 */
export const createApiKeyV1ApiKeysPost = async (apiKeyCreate: ApiKeyCreate, options?: Parameters<typeof axiosInstance>[1]): Promise<createApiKeyV1ApiKeysPostResponse> => {

  return axiosInstance<createApiKeyV1ApiKeysPostResponse>(getCreateApiKeyV1ApiKeysPostUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(apiKeyCreate)
  }
);}





export const getCreateApiKeyV1ApiKeysPostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createApiKeyV1ApiKeysPost>>, TError,{data: ApiKeyCreate}, TContext>, request?: SecondParameter<typeof axiosInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof createApiKeyV1ApiKeysPost>>, TError,{data: ApiKeyCreate}, TContext> => {

const mutationKey = ['createApiKeyV1ApiKeysPost'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createApiKeyV1ApiKeysPost>>, {data: ApiKeyCreate}> = (props) => {
          const {data} = props ?? {};

          return  createApiKeyV1ApiKeysPost(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CreateApiKeyV1ApiKeysPostMutationResult = NonNullable<Awaited<ReturnType<typeof createApiKeyV1ApiKeysPost>>>
    export type CreateApiKeyV1ApiKeysPostMutationBody = ApiKeyCreate
    export type CreateApiKeyV1ApiKeysPostMutationError = HTTPValidationError

    /**
 * @summary Create Api Key
 */
export const useCreateApiKeyV1ApiKeysPost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createApiKeyV1ApiKeysPost>>, TError,{data: ApiKeyCreate}, TContext>, request?: SecondParameter<typeof axiosInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createApiKeyV1ApiKeysPost>>,
        TError,
        {data: ApiKeyCreate},
        TContext
      > => {
      return useMutation(getCreateApiKeyV1ApiKeysPostMutationOptions(options), queryClient);
    }

export type listApiKeysV1ApiKeysGetResponse200 = {
  data: ApiKeyView[]
  status: 200
}

export type listApiKeysV1ApiKeysGetResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type listApiKeysV1ApiKeysGetResponseSuccess = (listApiKeysV1ApiKeysGetResponse200) & {
  headers: Headers;
};
export type listApiKeysV1ApiKeysGetResponseError = (listApiKeysV1ApiKeysGetResponse422) & {
  headers: Headers;
};

export type listApiKeysV1ApiKeysGetResponse = (listApiKeysV1ApiKeysGetResponseSuccess | listApiKeysV1ApiKeysGetResponseError)

export const getListApiKeysV1ApiKeysGetUrl = () => {




  return `/v1/api-keys`
}

/**
 * Return all active API keys for the tenant.
 * @summary List Api Keys
 */
export const listApiKeysV1ApiKeysGet = async ( options?: Parameters<typeof axiosInstance>[1]): Promise<listApiKeysV1ApiKeysGetResponse> => {

  return axiosInstance<listApiKeysV1ApiKeysGetResponse>(getListApiKeysV1ApiKeysGetUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getListApiKeysV1ApiKeysGetQueryKey = () => {
    return [
    `/v1/api-keys`
    ] as const;
    }


export const getListApiKeysV1ApiKeysGetQueryOptions = <TData = Awaited<ReturnType<typeof listApiKeysV1ApiKeysGet>>, TError = HTTPValidationError>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listApiKeysV1ApiKeysGet>>, TError, TData>>, request?: SecondParameter<typeof axiosInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListApiKeysV1ApiKeysGetQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listApiKeysV1ApiKeysGet>>> = ({ signal }) => listApiKeysV1ApiKeysGet({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listApiKeysV1ApiKeysGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListApiKeysV1ApiKeysGetQueryResult = NonNullable<Awaited<ReturnType<typeof listApiKeysV1ApiKeysGet>>>
export type ListApiKeysV1ApiKeysGetQueryError = HTTPValidationError


export function useListApiKeysV1ApiKeysGet<TData = Awaited<ReturnType<typeof listApiKeysV1ApiKeysGet>>, TError = HTTPValidationError>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listApiKeysV1ApiKeysGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listApiKeysV1ApiKeysGet>>,
          TError,
          Awaited<ReturnType<typeof listApiKeysV1ApiKeysGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axiosInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListApiKeysV1ApiKeysGet<TData = Awaited<ReturnType<typeof listApiKeysV1ApiKeysGet>>, TError = HTTPValidationError>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listApiKeysV1ApiKeysGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listApiKeysV1ApiKeysGet>>,
          TError,
          Awaited<ReturnType<typeof listApiKeysV1ApiKeysGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axiosInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListApiKeysV1ApiKeysGet<TData = Awaited<ReturnType<typeof listApiKeysV1ApiKeysGet>>, TError = HTTPValidationError>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listApiKeysV1ApiKeysGet>>, TError, TData>>, request?: SecondParameter<typeof axiosInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List Api Keys
 */

export function useListApiKeysV1ApiKeysGet<TData = Awaited<ReturnType<typeof listApiKeysV1ApiKeysGet>>, TError = HTTPValidationError>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listApiKeysV1ApiKeysGet>>, TError, TData>>, request?: SecondParameter<typeof axiosInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListApiKeysV1ApiKeysGetQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}







export type revokeApiKeyV1ApiKeysKeyIdDeleteResponse204 = {
  data: void
  status: 204
}

export type revokeApiKeyV1ApiKeysKeyIdDeleteResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type revokeApiKeyV1ApiKeysKeyIdDeleteResponseSuccess = (revokeApiKeyV1ApiKeysKeyIdDeleteResponse204) & {
  headers: Headers;
};
export type revokeApiKeyV1ApiKeysKeyIdDeleteResponseError = (revokeApiKeyV1ApiKeysKeyIdDeleteResponse422) & {
  headers: Headers;
};

export type revokeApiKeyV1ApiKeysKeyIdDeleteResponse = (revokeApiKeyV1ApiKeysKeyIdDeleteResponseSuccess | revokeApiKeyV1ApiKeysKeyIdDeleteResponseError)

export const getRevokeApiKeyV1ApiKeysKeyIdDeleteUrl = (keyId: string,) => {




  return `/v1/api-keys/${keyId}`
}

/**
 * Revoke an API key by ID. Requires admin scope.
 * @summary Revoke Api Key
 */
export const revokeApiKeyV1ApiKeysKeyIdDelete = async (keyId: string, options?: Parameters<typeof axiosInstance>[1]): Promise<revokeApiKeyV1ApiKeysKeyIdDeleteResponse> => {

  return axiosInstance<revokeApiKeyV1ApiKeysKeyIdDeleteResponse>(getRevokeApiKeyV1ApiKeysKeyIdDeleteUrl(keyId),
  {
    ...options,
    method: 'DELETE'


  }
);}





export const getRevokeApiKeyV1ApiKeysKeyIdDeleteMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof revokeApiKeyV1ApiKeysKeyIdDelete>>, TError,{keyId: string}, TContext>, request?: SecondParameter<typeof axiosInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof revokeApiKeyV1ApiKeysKeyIdDelete>>, TError,{keyId: string}, TContext> => {

const mutationKey = ['revokeApiKeyV1ApiKeysKeyIdDelete'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof revokeApiKeyV1ApiKeysKeyIdDelete>>, {keyId: string}> = (props) => {
          const {keyId} = props ?? {};

          return  revokeApiKeyV1ApiKeysKeyIdDelete(keyId,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type RevokeApiKeyV1ApiKeysKeyIdDeleteMutationResult = NonNullable<Awaited<ReturnType<typeof revokeApiKeyV1ApiKeysKeyIdDelete>>>

    export type RevokeApiKeyV1ApiKeysKeyIdDeleteMutationError = HTTPValidationError

    /**
 * @summary Revoke Api Key
 */
export const useRevokeApiKeyV1ApiKeysKeyIdDelete = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof revokeApiKeyV1ApiKeysKeyIdDelete>>, TError,{keyId: string}, TContext>, request?: SecondParameter<typeof axiosInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof revokeApiKeyV1ApiKeysKeyIdDelete>>,
        TError,
        {keyId: string},
        TContext
      > => {
      return useMutation(getRevokeApiKeyV1ApiKeysKeyIdDeleteMutationOptions(options), queryClient);
    }

export type createRoleV1RolesPostResponse201 = {
  data: RoleView
  status: 201
}

export type createRoleV1RolesPostResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type createRoleV1RolesPostResponseSuccess = (createRoleV1RolesPostResponse201) & {
  headers: Headers;
};
export type createRoleV1RolesPostResponseError = (createRoleV1RolesPostResponse422) & {
  headers: Headers;
};

export type createRoleV1RolesPostResponse = (createRoleV1RolesPostResponseSuccess | createRoleV1RolesPostResponseError)

export const getCreateRoleV1RolesPostUrl = () => {




  return `/v1/roles`
}

/**
 * Create a new role (admin only).
 * @summary Create Role
 */
export const createRoleV1RolesPost = async (roleCreate: RoleCreate, options?: Parameters<typeof axiosInstance>[1]): Promise<createRoleV1RolesPostResponse> => {

  return axiosInstance<createRoleV1RolesPostResponse>(getCreateRoleV1RolesPostUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(roleCreate)
  }
);}





export const getCreateRoleV1RolesPostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createRoleV1RolesPost>>, TError,{data: RoleCreate}, TContext>, request?: SecondParameter<typeof axiosInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof createRoleV1RolesPost>>, TError,{data: RoleCreate}, TContext> => {

const mutationKey = ['createRoleV1RolesPost'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createRoleV1RolesPost>>, {data: RoleCreate}> = (props) => {
          const {data} = props ?? {};

          return  createRoleV1RolesPost(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CreateRoleV1RolesPostMutationResult = NonNullable<Awaited<ReturnType<typeof createRoleV1RolesPost>>>
    export type CreateRoleV1RolesPostMutationBody = RoleCreate
    export type CreateRoleV1RolesPostMutationError = HTTPValidationError

    /**
 * @summary Create Role
 */
export const useCreateRoleV1RolesPost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createRoleV1RolesPost>>, TError,{data: RoleCreate}, TContext>, request?: SecondParameter<typeof axiosInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createRoleV1RolesPost>>,
        TError,
        {data: RoleCreate},
        TContext
      > => {
      return useMutation(getCreateRoleV1RolesPostMutationOptions(options), queryClient);
    }

export type listRolesV1RolesGetResponse200 = {
  data: RoleView[]
  status: 200
}

export type listRolesV1RolesGetResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type listRolesV1RolesGetResponseSuccess = (listRolesV1RolesGetResponse200) & {
  headers: Headers;
};
export type listRolesV1RolesGetResponseError = (listRolesV1RolesGetResponse422) & {
  headers: Headers;
};

export type listRolesV1RolesGetResponse = (listRolesV1RolesGetResponseSuccess | listRolesV1RolesGetResponseError)

export const getListRolesV1RolesGetUrl = () => {




  return `/v1/roles`
}

/**
 * List all roles for the current tenant.
 * @summary List Roles
 */
export const listRolesV1RolesGet = async ( options?: Parameters<typeof axiosInstance>[1]): Promise<listRolesV1RolesGetResponse> => {

  return axiosInstance<listRolesV1RolesGetResponse>(getListRolesV1RolesGetUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getListRolesV1RolesGetQueryKey = () => {
    return [
    `/v1/roles`
    ] as const;
    }


export const getListRolesV1RolesGetQueryOptions = <TData = Awaited<ReturnType<typeof listRolesV1RolesGet>>, TError = HTTPValidationError>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listRolesV1RolesGet>>, TError, TData>>, request?: SecondParameter<typeof axiosInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListRolesV1RolesGetQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listRolesV1RolesGet>>> = ({ signal }) => listRolesV1RolesGet({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listRolesV1RolesGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListRolesV1RolesGetQueryResult = NonNullable<Awaited<ReturnType<typeof listRolesV1RolesGet>>>
export type ListRolesV1RolesGetQueryError = HTTPValidationError


export function useListRolesV1RolesGet<TData = Awaited<ReturnType<typeof listRolesV1RolesGet>>, TError = HTTPValidationError>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listRolesV1RolesGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listRolesV1RolesGet>>,
          TError,
          Awaited<ReturnType<typeof listRolesV1RolesGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axiosInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListRolesV1RolesGet<TData = Awaited<ReturnType<typeof listRolesV1RolesGet>>, TError = HTTPValidationError>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listRolesV1RolesGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listRolesV1RolesGet>>,
          TError,
          Awaited<ReturnType<typeof listRolesV1RolesGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axiosInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListRolesV1RolesGet<TData = Awaited<ReturnType<typeof listRolesV1RolesGet>>, TError = HTTPValidationError>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listRolesV1RolesGet>>, TError, TData>>, request?: SecondParameter<typeof axiosInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List Roles
 */

export function useListRolesV1RolesGet<TData = Awaited<ReturnType<typeof listRolesV1RolesGet>>, TError = HTTPValidationError>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listRolesV1RolesGet>>, TError, TData>>, request?: SecondParameter<typeof axiosInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListRolesV1RolesGetQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}







export type createBindingV1RolesRoleIdBindingsPostResponse201 = {
  data: RoleBindingView
  status: 201
}

export type createBindingV1RolesRoleIdBindingsPostResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type createBindingV1RolesRoleIdBindingsPostResponseSuccess = (createBindingV1RolesRoleIdBindingsPostResponse201) & {
  headers: Headers;
};
export type createBindingV1RolesRoleIdBindingsPostResponseError = (createBindingV1RolesRoleIdBindingsPostResponse422) & {
  headers: Headers;
};

export type createBindingV1RolesRoleIdBindingsPostResponse = (createBindingV1RolesRoleIdBindingsPostResponseSuccess | createBindingV1RolesRoleIdBindingsPostResponseError)

export const getCreateBindingV1RolesRoleIdBindingsPostUrl = (roleId: string,) => {




  return `/v1/roles/${roleId}/bindings`
}

/**
 * Bind an API key subject to a role (admin only).
 * @summary Create Binding
 */
export const createBindingV1RolesRoleIdBindingsPost = async (roleId: string,
    roleBindingCreate: RoleBindingCreate, options?: Parameters<typeof axiosInstance>[1]): Promise<createBindingV1RolesRoleIdBindingsPostResponse> => {

  return axiosInstance<createBindingV1RolesRoleIdBindingsPostResponse>(getCreateBindingV1RolesRoleIdBindingsPostUrl(roleId),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(roleBindingCreate)
  }
);}





export const getCreateBindingV1RolesRoleIdBindingsPostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createBindingV1RolesRoleIdBindingsPost>>, TError,{roleId: string;data: RoleBindingCreate}, TContext>, request?: SecondParameter<typeof axiosInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof createBindingV1RolesRoleIdBindingsPost>>, TError,{roleId: string;data: RoleBindingCreate}, TContext> => {

const mutationKey = ['createBindingV1RolesRoleIdBindingsPost'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createBindingV1RolesRoleIdBindingsPost>>, {roleId: string;data: RoleBindingCreate}> = (props) => {
          const {roleId,data} = props ?? {};

          return  createBindingV1RolesRoleIdBindingsPost(roleId,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CreateBindingV1RolesRoleIdBindingsPostMutationResult = NonNullable<Awaited<ReturnType<typeof createBindingV1RolesRoleIdBindingsPost>>>
    export type CreateBindingV1RolesRoleIdBindingsPostMutationBody = RoleBindingCreate
    export type CreateBindingV1RolesRoleIdBindingsPostMutationError = HTTPValidationError

    /**
 * @summary Create Binding
 */
export const useCreateBindingV1RolesRoleIdBindingsPost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createBindingV1RolesRoleIdBindingsPost>>, TError,{roleId: string;data: RoleBindingCreate}, TContext>, request?: SecondParameter<typeof axiosInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createBindingV1RolesRoleIdBindingsPost>>,
        TError,
        {roleId: string;data: RoleBindingCreate},
        TContext
      > => {
      return useMutation(getCreateBindingV1RolesRoleIdBindingsPostMutationOptions(options), queryClient);
    }

export type deleteBindingV1RolesRoleIdBindingsBindingIdDeleteResponse204 = {
  data: void
  status: 204
}

export type deleteBindingV1RolesRoleIdBindingsBindingIdDeleteResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type deleteBindingV1RolesRoleIdBindingsBindingIdDeleteResponseSuccess = (deleteBindingV1RolesRoleIdBindingsBindingIdDeleteResponse204) & {
  headers: Headers;
};
export type deleteBindingV1RolesRoleIdBindingsBindingIdDeleteResponseError = (deleteBindingV1RolesRoleIdBindingsBindingIdDeleteResponse422) & {
  headers: Headers;
};

export type deleteBindingV1RolesRoleIdBindingsBindingIdDeleteResponse = (deleteBindingV1RolesRoleIdBindingsBindingIdDeleteResponseSuccess | deleteBindingV1RolesRoleIdBindingsBindingIdDeleteResponseError)

export const getDeleteBindingV1RolesRoleIdBindingsBindingIdDeleteUrl = (roleId: string,
    bindingId: string,) => {




  return `/v1/roles/${roleId}/bindings/${bindingId}`
}

/**
 * Remove a role binding (admin only).
 * @summary Delete Binding
 */
export const deleteBindingV1RolesRoleIdBindingsBindingIdDelete = async (roleId: string,
    bindingId: string, options?: Parameters<typeof axiosInstance>[1]): Promise<deleteBindingV1RolesRoleIdBindingsBindingIdDeleteResponse> => {

  return axiosInstance<deleteBindingV1RolesRoleIdBindingsBindingIdDeleteResponse>(getDeleteBindingV1RolesRoleIdBindingsBindingIdDeleteUrl(roleId,bindingId),
  {
    ...options,
    method: 'DELETE'


  }
);}





export const getDeleteBindingV1RolesRoleIdBindingsBindingIdDeleteMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteBindingV1RolesRoleIdBindingsBindingIdDelete>>, TError,{roleId: string;bindingId: string}, TContext>, request?: SecondParameter<typeof axiosInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteBindingV1RolesRoleIdBindingsBindingIdDelete>>, TError,{roleId: string;bindingId: string}, TContext> => {

const mutationKey = ['deleteBindingV1RolesRoleIdBindingsBindingIdDelete'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteBindingV1RolesRoleIdBindingsBindingIdDelete>>, {roleId: string;bindingId: string}> = (props) => {
          const {roleId,bindingId} = props ?? {};

          return  deleteBindingV1RolesRoleIdBindingsBindingIdDelete(roleId,bindingId,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteBindingV1RolesRoleIdBindingsBindingIdDeleteMutationResult = NonNullable<Awaited<ReturnType<typeof deleteBindingV1RolesRoleIdBindingsBindingIdDelete>>>

    export type DeleteBindingV1RolesRoleIdBindingsBindingIdDeleteMutationError = HTTPValidationError

    /**
 * @summary Delete Binding
 */
export const useDeleteBindingV1RolesRoleIdBindingsBindingIdDelete = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteBindingV1RolesRoleIdBindingsBindingIdDelete>>, TError,{roleId: string;bindingId: string}, TContext>, request?: SecondParameter<typeof axiosInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteBindingV1RolesRoleIdBindingsBindingIdDelete>>,
        TError,
        {roleId: string;bindingId: string},
        TContext
      > => {
      return useMutation(getDeleteBindingV1RolesRoleIdBindingsBindingIdDeleteMutationOptions(options), queryClient);
    }

export type createPermissionV1RolesRoleIdPermissionsPostResponse201 = {
  data: ToolPermissionView
  status: 201
}

export type createPermissionV1RolesRoleIdPermissionsPostResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type createPermissionV1RolesRoleIdPermissionsPostResponseSuccess = (createPermissionV1RolesRoleIdPermissionsPostResponse201) & {
  headers: Headers;
};
export type createPermissionV1RolesRoleIdPermissionsPostResponseError = (createPermissionV1RolesRoleIdPermissionsPostResponse422) & {
  headers: Headers;
};

export type createPermissionV1RolesRoleIdPermissionsPostResponse = (createPermissionV1RolesRoleIdPermissionsPostResponseSuccess | createPermissionV1RolesRoleIdPermissionsPostResponseError)

export const getCreatePermissionV1RolesRoleIdPermissionsPostUrl = (roleId: string,) => {




  return `/v1/roles/${roleId}/permissions`
}

/**
 * Attach a tool permission rule to a role (admin only).
 * @summary Create Permission
 */
export const createPermissionV1RolesRoleIdPermissionsPost = async (roleId: string,
    toolPermissionCreate: ToolPermissionCreate, options?: Parameters<typeof axiosInstance>[1]): Promise<createPermissionV1RolesRoleIdPermissionsPostResponse> => {

  return axiosInstance<createPermissionV1RolesRoleIdPermissionsPostResponse>(getCreatePermissionV1RolesRoleIdPermissionsPostUrl(roleId),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(toolPermissionCreate)
  }
);}





export const getCreatePermissionV1RolesRoleIdPermissionsPostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createPermissionV1RolesRoleIdPermissionsPost>>, TError,{roleId: string;data: ToolPermissionCreate}, TContext>, request?: SecondParameter<typeof axiosInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof createPermissionV1RolesRoleIdPermissionsPost>>, TError,{roleId: string;data: ToolPermissionCreate}, TContext> => {

const mutationKey = ['createPermissionV1RolesRoleIdPermissionsPost'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createPermissionV1RolesRoleIdPermissionsPost>>, {roleId: string;data: ToolPermissionCreate}> = (props) => {
          const {roleId,data} = props ?? {};

          return  createPermissionV1RolesRoleIdPermissionsPost(roleId,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CreatePermissionV1RolesRoleIdPermissionsPostMutationResult = NonNullable<Awaited<ReturnType<typeof createPermissionV1RolesRoleIdPermissionsPost>>>
    export type CreatePermissionV1RolesRoleIdPermissionsPostMutationBody = ToolPermissionCreate
    export type CreatePermissionV1RolesRoleIdPermissionsPostMutationError = HTTPValidationError

    /**
 * @summary Create Permission
 */
export const useCreatePermissionV1RolesRoleIdPermissionsPost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createPermissionV1RolesRoleIdPermissionsPost>>, TError,{roleId: string;data: ToolPermissionCreate}, TContext>, request?: SecondParameter<typeof axiosInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createPermissionV1RolesRoleIdPermissionsPost>>,
        TError,
        {roleId: string;data: ToolPermissionCreate},
        TContext
      > => {
      return useMutation(getCreatePermissionV1RolesRoleIdPermissionsPostMutationOptions(options), queryClient);
    }

export type deletePermissionV1RolesRoleIdPermissionsPermissionIdDeleteResponse204 = {
  data: void
  status: 204
}

export type deletePermissionV1RolesRoleIdPermissionsPermissionIdDeleteResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type deletePermissionV1RolesRoleIdPermissionsPermissionIdDeleteResponseSuccess = (deletePermissionV1RolesRoleIdPermissionsPermissionIdDeleteResponse204) & {
  headers: Headers;
};
export type deletePermissionV1RolesRoleIdPermissionsPermissionIdDeleteResponseError = (deletePermissionV1RolesRoleIdPermissionsPermissionIdDeleteResponse422) & {
  headers: Headers;
};

export type deletePermissionV1RolesRoleIdPermissionsPermissionIdDeleteResponse = (deletePermissionV1RolesRoleIdPermissionsPermissionIdDeleteResponseSuccess | deletePermissionV1RolesRoleIdPermissionsPermissionIdDeleteResponseError)

export const getDeletePermissionV1RolesRoleIdPermissionsPermissionIdDeleteUrl = (roleId: string,
    permissionId: string,) => {




  return `/v1/roles/${roleId}/permissions/${permissionId}`
}

/**
 * Remove a tool permission rule from a role (admin only).
 * @summary Delete Permission
 */
export const deletePermissionV1RolesRoleIdPermissionsPermissionIdDelete = async (roleId: string,
    permissionId: string, options?: Parameters<typeof axiosInstance>[1]): Promise<deletePermissionV1RolesRoleIdPermissionsPermissionIdDeleteResponse> => {

  return axiosInstance<deletePermissionV1RolesRoleIdPermissionsPermissionIdDeleteResponse>(getDeletePermissionV1RolesRoleIdPermissionsPermissionIdDeleteUrl(roleId,permissionId),
  {
    ...options,
    method: 'DELETE'


  }
);}





export const getDeletePermissionV1RolesRoleIdPermissionsPermissionIdDeleteMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deletePermissionV1RolesRoleIdPermissionsPermissionIdDelete>>, TError,{roleId: string;permissionId: string}, TContext>, request?: SecondParameter<typeof axiosInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof deletePermissionV1RolesRoleIdPermissionsPermissionIdDelete>>, TError,{roleId: string;permissionId: string}, TContext> => {

const mutationKey = ['deletePermissionV1RolesRoleIdPermissionsPermissionIdDelete'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deletePermissionV1RolesRoleIdPermissionsPermissionIdDelete>>, {roleId: string;permissionId: string}> = (props) => {
          const {roleId,permissionId} = props ?? {};

          return  deletePermissionV1RolesRoleIdPermissionsPermissionIdDelete(roleId,permissionId,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeletePermissionV1RolesRoleIdPermissionsPermissionIdDeleteMutationResult = NonNullable<Awaited<ReturnType<typeof deletePermissionV1RolesRoleIdPermissionsPermissionIdDelete>>>

    export type DeletePermissionV1RolesRoleIdPermissionsPermissionIdDeleteMutationError = HTTPValidationError

    /**
 * @summary Delete Permission
 */
export const useDeletePermissionV1RolesRoleIdPermissionsPermissionIdDelete = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deletePermissionV1RolesRoleIdPermissionsPermissionIdDelete>>, TError,{roleId: string;permissionId: string}, TContext>, request?: SecondParameter<typeof axiosInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deletePermissionV1RolesRoleIdPermissionsPermissionIdDelete>>,
        TError,
        {roleId: string;permissionId: string},
        TContext
      > => {
      return useMutation(getDeletePermissionV1RolesRoleIdPermissionsPermissionIdDeleteMutationOptions(options), queryClient);
    }

export type createPolicyV1RateLimitPoliciesPostResponse201 = {
  data: RateLimitPolicyView
  status: 201
}

export type createPolicyV1RateLimitPoliciesPostResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type createPolicyV1RateLimitPoliciesPostResponseSuccess = (createPolicyV1RateLimitPoliciesPostResponse201) & {
  headers: Headers;
};
export type createPolicyV1RateLimitPoliciesPostResponseError = (createPolicyV1RateLimitPoliciesPostResponse422) & {
  headers: Headers;
};

export type createPolicyV1RateLimitPoliciesPostResponse = (createPolicyV1RateLimitPoliciesPostResponseSuccess | createPolicyV1RateLimitPoliciesPostResponseError)

export const getCreatePolicyV1RateLimitPoliciesPostUrl = () => {




  return `/v1/rate-limit-policies`
}

/**
 * Create a new rate-limit policy (admin only).
 * @summary Create Policy
 */
export const createPolicyV1RateLimitPoliciesPost = async (rateLimitPolicyCreate: RateLimitPolicyCreate, options?: Parameters<typeof axiosInstance>[1]): Promise<createPolicyV1RateLimitPoliciesPostResponse> => {

  return axiosInstance<createPolicyV1RateLimitPoliciesPostResponse>(getCreatePolicyV1RateLimitPoliciesPostUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(rateLimitPolicyCreate)
  }
);}





export const getCreatePolicyV1RateLimitPoliciesPostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createPolicyV1RateLimitPoliciesPost>>, TError,{data: RateLimitPolicyCreate}, TContext>, request?: SecondParameter<typeof axiosInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof createPolicyV1RateLimitPoliciesPost>>, TError,{data: RateLimitPolicyCreate}, TContext> => {

const mutationKey = ['createPolicyV1RateLimitPoliciesPost'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createPolicyV1RateLimitPoliciesPost>>, {data: RateLimitPolicyCreate}> = (props) => {
          const {data} = props ?? {};

          return  createPolicyV1RateLimitPoliciesPost(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CreatePolicyV1RateLimitPoliciesPostMutationResult = NonNullable<Awaited<ReturnType<typeof createPolicyV1RateLimitPoliciesPost>>>
    export type CreatePolicyV1RateLimitPoliciesPostMutationBody = RateLimitPolicyCreate
    export type CreatePolicyV1RateLimitPoliciesPostMutationError = HTTPValidationError

    /**
 * @summary Create Policy
 */
export const useCreatePolicyV1RateLimitPoliciesPost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createPolicyV1RateLimitPoliciesPost>>, TError,{data: RateLimitPolicyCreate}, TContext>, request?: SecondParameter<typeof axiosInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createPolicyV1RateLimitPoliciesPost>>,
        TError,
        {data: RateLimitPolicyCreate},
        TContext
      > => {
      return useMutation(getCreatePolicyV1RateLimitPoliciesPostMutationOptions(options), queryClient);
    }

export type listPoliciesV1RateLimitPoliciesGetResponse200 = {
  data: RateLimitPolicyView[]
  status: 200
}

export type listPoliciesV1RateLimitPoliciesGetResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type listPoliciesV1RateLimitPoliciesGetResponseSuccess = (listPoliciesV1RateLimitPoliciesGetResponse200) & {
  headers: Headers;
};
export type listPoliciesV1RateLimitPoliciesGetResponseError = (listPoliciesV1RateLimitPoliciesGetResponse422) & {
  headers: Headers;
};

export type listPoliciesV1RateLimitPoliciesGetResponse = (listPoliciesV1RateLimitPoliciesGetResponseSuccess | listPoliciesV1RateLimitPoliciesGetResponseError)

export const getListPoliciesV1RateLimitPoliciesGetUrl = () => {




  return `/v1/rate-limit-policies`
}

/**
 * List all rate-limit policies for the current tenant.
 * @summary List Policies
 */
export const listPoliciesV1RateLimitPoliciesGet = async ( options?: Parameters<typeof axiosInstance>[1]): Promise<listPoliciesV1RateLimitPoliciesGetResponse> => {

  return axiosInstance<listPoliciesV1RateLimitPoliciesGetResponse>(getListPoliciesV1RateLimitPoliciesGetUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getListPoliciesV1RateLimitPoliciesGetQueryKey = () => {
    return [
    `/v1/rate-limit-policies`
    ] as const;
    }


export const getListPoliciesV1RateLimitPoliciesGetQueryOptions = <TData = Awaited<ReturnType<typeof listPoliciesV1RateLimitPoliciesGet>>, TError = HTTPValidationError>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listPoliciesV1RateLimitPoliciesGet>>, TError, TData>>, request?: SecondParameter<typeof axiosInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListPoliciesV1RateLimitPoliciesGetQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listPoliciesV1RateLimitPoliciesGet>>> = ({ signal }) => listPoliciesV1RateLimitPoliciesGet({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listPoliciesV1RateLimitPoliciesGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListPoliciesV1RateLimitPoliciesGetQueryResult = NonNullable<Awaited<ReturnType<typeof listPoliciesV1RateLimitPoliciesGet>>>
export type ListPoliciesV1RateLimitPoliciesGetQueryError = HTTPValidationError


export function useListPoliciesV1RateLimitPoliciesGet<TData = Awaited<ReturnType<typeof listPoliciesV1RateLimitPoliciesGet>>, TError = HTTPValidationError>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listPoliciesV1RateLimitPoliciesGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listPoliciesV1RateLimitPoliciesGet>>,
          TError,
          Awaited<ReturnType<typeof listPoliciesV1RateLimitPoliciesGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axiosInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListPoliciesV1RateLimitPoliciesGet<TData = Awaited<ReturnType<typeof listPoliciesV1RateLimitPoliciesGet>>, TError = HTTPValidationError>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listPoliciesV1RateLimitPoliciesGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listPoliciesV1RateLimitPoliciesGet>>,
          TError,
          Awaited<ReturnType<typeof listPoliciesV1RateLimitPoliciesGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axiosInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListPoliciesV1RateLimitPoliciesGet<TData = Awaited<ReturnType<typeof listPoliciesV1RateLimitPoliciesGet>>, TError = HTTPValidationError>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listPoliciesV1RateLimitPoliciesGet>>, TError, TData>>, request?: SecondParameter<typeof axiosInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List Policies
 */

export function useListPoliciesV1RateLimitPoliciesGet<TData = Awaited<ReturnType<typeof listPoliciesV1RateLimitPoliciesGet>>, TError = HTTPValidationError>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listPoliciesV1RateLimitPoliciesGet>>, TError, TData>>, request?: SecondParameter<typeof axiosInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListPoliciesV1RateLimitPoliciesGetQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}







export type updatePolicyV1RateLimitPoliciesPolicyIdPatchResponse200 = {
  data: RateLimitPolicyView
  status: 200
}

export type updatePolicyV1RateLimitPoliciesPolicyIdPatchResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type updatePolicyV1RateLimitPoliciesPolicyIdPatchResponseSuccess = (updatePolicyV1RateLimitPoliciesPolicyIdPatchResponse200) & {
  headers: Headers;
};
export type updatePolicyV1RateLimitPoliciesPolicyIdPatchResponseError = (updatePolicyV1RateLimitPoliciesPolicyIdPatchResponse422) & {
  headers: Headers;
};

export type updatePolicyV1RateLimitPoliciesPolicyIdPatchResponse = (updatePolicyV1RateLimitPoliciesPolicyIdPatchResponseSuccess | updatePolicyV1RateLimitPoliciesPolicyIdPatchResponseError)

export const getUpdatePolicyV1RateLimitPoliciesPolicyIdPatchUrl = (policyId: string,) => {




  return `/v1/rate-limit-policies/${policyId}`
}

/**
 * Update an existing rate-limit policy (admin only).
 * @summary Update Policy
 */
export const updatePolicyV1RateLimitPoliciesPolicyIdPatch = async (policyId: string,
    rateLimitPolicyUpdate: RateLimitPolicyUpdate, options?: Parameters<typeof axiosInstance>[1]): Promise<updatePolicyV1RateLimitPoliciesPolicyIdPatchResponse> => {

  return axiosInstance<updatePolicyV1RateLimitPoliciesPolicyIdPatchResponse>(getUpdatePolicyV1RateLimitPoliciesPolicyIdPatchUrl(policyId),
  {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(rateLimitPolicyUpdate)
  }
);}





export const getUpdatePolicyV1RateLimitPoliciesPolicyIdPatchMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updatePolicyV1RateLimitPoliciesPolicyIdPatch>>, TError,{policyId: string;data: RateLimitPolicyUpdate}, TContext>, request?: SecondParameter<typeof axiosInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof updatePolicyV1RateLimitPoliciesPolicyIdPatch>>, TError,{policyId: string;data: RateLimitPolicyUpdate}, TContext> => {

const mutationKey = ['updatePolicyV1RateLimitPoliciesPolicyIdPatch'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updatePolicyV1RateLimitPoliciesPolicyIdPatch>>, {policyId: string;data: RateLimitPolicyUpdate}> = (props) => {
          const {policyId,data} = props ?? {};

          return  updatePolicyV1RateLimitPoliciesPolicyIdPatch(policyId,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UpdatePolicyV1RateLimitPoliciesPolicyIdPatchMutationResult = NonNullable<Awaited<ReturnType<typeof updatePolicyV1RateLimitPoliciesPolicyIdPatch>>>
    export type UpdatePolicyV1RateLimitPoliciesPolicyIdPatchMutationBody = RateLimitPolicyUpdate
    export type UpdatePolicyV1RateLimitPoliciesPolicyIdPatchMutationError = HTTPValidationError

    /**
 * @summary Update Policy
 */
export const useUpdatePolicyV1RateLimitPoliciesPolicyIdPatch = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updatePolicyV1RateLimitPoliciesPolicyIdPatch>>, TError,{policyId: string;data: RateLimitPolicyUpdate}, TContext>, request?: SecondParameter<typeof axiosInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updatePolicyV1RateLimitPoliciesPolicyIdPatch>>,
        TError,
        {policyId: string;data: RateLimitPolicyUpdate},
        TContext
      > => {
      return useMutation(getUpdatePolicyV1RateLimitPoliciesPolicyIdPatchMutationOptions(options), queryClient);
    }

export type deletePolicyV1RateLimitPoliciesPolicyIdDeleteResponse204 = {
  data: void
  status: 204
}

export type deletePolicyV1RateLimitPoliciesPolicyIdDeleteResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type deletePolicyV1RateLimitPoliciesPolicyIdDeleteResponseSuccess = (deletePolicyV1RateLimitPoliciesPolicyIdDeleteResponse204) & {
  headers: Headers;
};
export type deletePolicyV1RateLimitPoliciesPolicyIdDeleteResponseError = (deletePolicyV1RateLimitPoliciesPolicyIdDeleteResponse422) & {
  headers: Headers;
};

export type deletePolicyV1RateLimitPoliciesPolicyIdDeleteResponse = (deletePolicyV1RateLimitPoliciesPolicyIdDeleteResponseSuccess | deletePolicyV1RateLimitPoliciesPolicyIdDeleteResponseError)

export const getDeletePolicyV1RateLimitPoliciesPolicyIdDeleteUrl = (policyId: string,) => {




  return `/v1/rate-limit-policies/${policyId}`
}

/**
 * Delete a rate-limit policy (admin only).
 * @summary Delete Policy
 */
export const deletePolicyV1RateLimitPoliciesPolicyIdDelete = async (policyId: string, options?: Parameters<typeof axiosInstance>[1]): Promise<deletePolicyV1RateLimitPoliciesPolicyIdDeleteResponse> => {

  return axiosInstance<deletePolicyV1RateLimitPoliciesPolicyIdDeleteResponse>(getDeletePolicyV1RateLimitPoliciesPolicyIdDeleteUrl(policyId),
  {
    ...options,
    method: 'DELETE'


  }
);}





export const getDeletePolicyV1RateLimitPoliciesPolicyIdDeleteMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deletePolicyV1RateLimitPoliciesPolicyIdDelete>>, TError,{policyId: string}, TContext>, request?: SecondParameter<typeof axiosInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof deletePolicyV1RateLimitPoliciesPolicyIdDelete>>, TError,{policyId: string}, TContext> => {

const mutationKey = ['deletePolicyV1RateLimitPoliciesPolicyIdDelete'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deletePolicyV1RateLimitPoliciesPolicyIdDelete>>, {policyId: string}> = (props) => {
          const {policyId} = props ?? {};

          return  deletePolicyV1RateLimitPoliciesPolicyIdDelete(policyId,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeletePolicyV1RateLimitPoliciesPolicyIdDeleteMutationResult = NonNullable<Awaited<ReturnType<typeof deletePolicyV1RateLimitPoliciesPolicyIdDelete>>>

    export type DeletePolicyV1RateLimitPoliciesPolicyIdDeleteMutationError = HTTPValidationError

    /**
 * @summary Delete Policy
 */
export const useDeletePolicyV1RateLimitPoliciesPolicyIdDelete = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deletePolicyV1RateLimitPoliciesPolicyIdDelete>>, TError,{policyId: string}, TContext>, request?: SecondParameter<typeof axiosInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deletePolicyV1RateLimitPoliciesPolicyIdDelete>>,
        TError,
        {policyId: string},
        TContext
      > => {
      return useMutation(getDeletePolicyV1RateLimitPoliciesPolicyIdDeleteMutationOptions(options), queryClient);
    }

export type listAuditLogsV1AuditGetResponse200 = {
  data: AuditLogView[]
  status: 200
}

export type listAuditLogsV1AuditGetResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type listAuditLogsV1AuditGetResponseSuccess = (listAuditLogsV1AuditGetResponse200) & {
  headers: Headers;
};
export type listAuditLogsV1AuditGetResponseError = (listAuditLogsV1AuditGetResponse422) & {
  headers: Headers;
};

export type listAuditLogsV1AuditGetResponse = (listAuditLogsV1AuditGetResponseSuccess | listAuditLogsV1AuditGetResponseError)

export const getListAuditLogsV1AuditGetUrl = (params?: ListAuditLogsV1AuditGetParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/v1/audit?${stringifiedParams}` : `/v1/audit`
}

/**
 * Return audit log entries for the current tenant. Admin scope required.
 *
 * Results are ordered by created_at descending (newest first).
 * @summary List Audit Logs
 */
export const listAuditLogsV1AuditGet = async (params?: ListAuditLogsV1AuditGetParams, options?: Parameters<typeof axiosInstance>[1]): Promise<listAuditLogsV1AuditGetResponse> => {

  return axiosInstance<listAuditLogsV1AuditGetResponse>(getListAuditLogsV1AuditGetUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getListAuditLogsV1AuditGetQueryKey = (params?: ListAuditLogsV1AuditGetParams,) => {
    return [
    `/v1/audit`, ...(params ? [params] : [])
    ] as const;
    }


export const getListAuditLogsV1AuditGetQueryOptions = <TData = Awaited<ReturnType<typeof listAuditLogsV1AuditGet>>, TError = HTTPValidationError>(params?: ListAuditLogsV1AuditGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listAuditLogsV1AuditGet>>, TError, TData>>, request?: SecondParameter<typeof axiosInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListAuditLogsV1AuditGetQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listAuditLogsV1AuditGet>>> = ({ signal }) => listAuditLogsV1AuditGet(params, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listAuditLogsV1AuditGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListAuditLogsV1AuditGetQueryResult = NonNullable<Awaited<ReturnType<typeof listAuditLogsV1AuditGet>>>
export type ListAuditLogsV1AuditGetQueryError = HTTPValidationError


export function useListAuditLogsV1AuditGet<TData = Awaited<ReturnType<typeof listAuditLogsV1AuditGet>>, TError = HTTPValidationError>(
 params: undefined |  ListAuditLogsV1AuditGetParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listAuditLogsV1AuditGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listAuditLogsV1AuditGet>>,
          TError,
          Awaited<ReturnType<typeof listAuditLogsV1AuditGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axiosInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListAuditLogsV1AuditGet<TData = Awaited<ReturnType<typeof listAuditLogsV1AuditGet>>, TError = HTTPValidationError>(
 params?: ListAuditLogsV1AuditGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listAuditLogsV1AuditGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listAuditLogsV1AuditGet>>,
          TError,
          Awaited<ReturnType<typeof listAuditLogsV1AuditGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axiosInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListAuditLogsV1AuditGet<TData = Awaited<ReturnType<typeof listAuditLogsV1AuditGet>>, TError = HTTPValidationError>(
 params?: ListAuditLogsV1AuditGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listAuditLogsV1AuditGet>>, TError, TData>>, request?: SecondParameter<typeof axiosInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List Audit Logs
 */

export function useListAuditLogsV1AuditGet<TData = Awaited<ReturnType<typeof listAuditLogsV1AuditGet>>, TError = HTTPValidationError>(
 params?: ListAuditLogsV1AuditGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listAuditLogsV1AuditGet>>, TError, TData>>, request?: SecondParameter<typeof axiosInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListAuditLogsV1AuditGetQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}







export type mcpProxyMcpServerSlugPostResponse200 = {
  data: unknown
  status: 200
}

export type mcpProxyMcpServerSlugPostResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type mcpProxyMcpServerSlugPostResponseSuccess = (mcpProxyMcpServerSlugPostResponse200) & {
  headers: Headers;
};
export type mcpProxyMcpServerSlugPostResponseError = (mcpProxyMcpServerSlugPostResponse422) & {
  headers: Headers;
};

export type mcpProxyMcpServerSlugPostResponse = (mcpProxyMcpServerSlugPostResponseSuccess | mcpProxyMcpServerSlugPostResponseError)

export const getMcpProxyMcpServerSlugPostUrl = (serverSlug: string,) => {




  return `/mcp/${serverSlug}`
}

/**
 * Full MCP proxy pipeline: auth → registry → RBAC → rate-limit → forward.
 * @summary Mcp Proxy
 */
export const mcpProxyMcpServerSlugPost = async (serverSlug: string, options?: Parameters<typeof axiosInstance>[1]): Promise<mcpProxyMcpServerSlugPostResponse> => {

  return axiosInstance<mcpProxyMcpServerSlugPostResponse>(getMcpProxyMcpServerSlugPostUrl(serverSlug),
  {
    ...options,
    method: 'POST'


  }
);}





export const getMcpProxyMcpServerSlugPostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof mcpProxyMcpServerSlugPost>>, TError,{serverSlug: string}, TContext>, request?: SecondParameter<typeof axiosInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof mcpProxyMcpServerSlugPost>>, TError,{serverSlug: string}, TContext> => {

const mutationKey = ['mcpProxyMcpServerSlugPost'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof mcpProxyMcpServerSlugPost>>, {serverSlug: string}> = (props) => {
          const {serverSlug} = props ?? {};

          return  mcpProxyMcpServerSlugPost(serverSlug,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type McpProxyMcpServerSlugPostMutationResult = NonNullable<Awaited<ReturnType<typeof mcpProxyMcpServerSlugPost>>>

    export type McpProxyMcpServerSlugPostMutationError = HTTPValidationError

    /**
 * @summary Mcp Proxy
 */
export const useMcpProxyMcpServerSlugPost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof mcpProxyMcpServerSlugPost>>, TError,{serverSlug: string}, TContext>, request?: SecondParameter<typeof axiosInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof mcpProxyMcpServerSlugPost>>,
        TError,
        {serverSlug: string},
        TContext
      > => {
      return useMutation(getMcpProxyMcpServerSlugPostMutationOptions(options), queryClient);
    }
