apiVersion: v1
kind: Secret
metadata:
  name: {{ include "portcullis.fullname" . }}-secrets
  labels:
    {{- include "portcullis.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.secrets.apiKeyPepper }}
  API_KEY_PEPPER: {{ .Values.secrets.apiKeyPepper }}
  {{- end }}
  {{- if .Values.secrets.jwtJwksUrl }}
  JWT_JWKS_URL: {{ .Values.secrets.jwtJwksUrl }}
  {{- end }}
  {{- if .Values.secrets.jwtIssuer }}
  JWT_ISSUER: {{ .Values.secrets.jwtIssuer }}
  {{- end }}
  {{- if .Values.secrets.jwtAudience }}
  JWT_AUDIENCE: {{ .Values.secrets.jwtAudience }}
  {{- end }}
  {{- if .Values.secrets.ssoOidcClientSecret }}
  SSO_OIDC_CLIENT_SECRET: {{ .Values.secrets.ssoOidcClientSecret }}
  {{- end }}
  {{- if .Values.externalDatabase.enabled }}
  DATABASE_URL: postgresql+asyncpg://{{ .Values.externalDatabase.username }}:{{ .Values.externalDatabase.password }}@{{ .Values.externalDatabase.host }}:{{ .Values.externalDatabase.port }}/{{ .Values.externalDatabase.database }}?sslmode={{ .Values.externalDatabase.sslMode }}
  {{- else if .Values.postgresql.enabled }}
  DATABASE_URL: postgresql+asyncpg://portcullis:{{ .Values.postgresql.auth.password }}@{{ include "portcullis.postgresql.fullname" . }}:5432/portcullis
  {{- end }}
  {{- if .Values.redisExternal.enabled }}
  REDIS_URL: redis{{ if .Values.redisExternal.useSSL }}s{{ end }}://{{ if .Values.redisExternal.password }}:{{ .Values.redisExternal.password }}@{{ end }}{{ .Values.redisExternal.host }}:{{ .Values.redisExternal.port }}/{{ .Values.redisExternal.db }}
  {{- else if .Values.redis.mode == "sentinel" }}
  REDIS_URL: redis://{{ .Values.redis.sentinelMaster }}:6379/0
  {{- else if .Values.redis.mode == "cluster" }}
  REDIS_URL: redis://{{ include "portcullis.redis.fullname" . }}:6379/0
  {{- else }}
  REDIS_URL: redis://{{ include "portcullis.redis.fullname" . }}:6379/0
  {{- end }}