{{- if and .Values.web.enabled .Values.web.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "portcullis.fullname" . }}-web
  labels:
    {{- include "portcullis.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
  annotations:
    {{- toYaml .Values.web.ingress.annotations | nindent 4 }}
spec:
  ingressClassName: {{ .Values.web.ingress.className }}
  {{- if .Values.web.ingress.tls }}
  tls:
    {{- toYaml .Values.web.ingress.tls | nindent 4 }}
  {{- end }}
  rules:
    {{- toYaml .Values.web.ingress.hosts | nindent 4 }}
{{- end }}
